import os
import shutil
from rich.console import Console
from rich.progress import Progress

console = Console()

def start_fresh():
    """
    Deletes all output files (HTML, Markdown, CSV, etc.) generated by the main script.
    Preserves original JSON files and directory structure.
    """
    output_dir = "output_logs"

    if not os.path.exists(output_dir):
        console.print(f"[bold red]Error:[/bold red] The output directory '{output_dir}' does not exist.")
        return

    with Progress() as progress:
        task = progress.add_task("[cyan]Cleaning up output files...", total=100)

        try:
            # Delete the entire output_logs directory and its contents
            shutil.rmtree(output_dir)
            progress.update(task, advance=100)
            console.print(f"[bold green]Success:[/bold green] All output files have been removed.")
        except Exception as e:
            console.print(f"[bold red]Error:[/bold red] An error occurred while cleaning: {str(e)}")
            raise

if __name__ == "__main__":
    console.print("[bold blue]Starting fresh cleanup process...[/bold blue]")
    start_fresh()
